global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "ai-load-balancer"
    static_configs:
      - targets: ["ai-load-balancer:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
